@startuml
namespace Common{
    enum GameScene{
        Tutorial
        Forest
        City
        AirBattle
        FinalBoss
    }
    class SceneLoader
}
namespace Damages{
    interface IDamageApplicable{
        - ApplyDamage(Damage damage): void
    }
    class Damage
}
namespace Effects{
    class Shake
}
namespace Enemies{
    class BaseEnemy
    class Spider
    namespace Gimmick{
        class OperationReversal
        class MinusMagnet
    }
}
namespace Installers{
    class StageInstaller
}
namespace Managers{
    enum GameState{
        Ready
        Battle
        finished
    }
    class BGMFadeOut
    class GameInitializer
    class GameStartOption
    class GameStateManager
    class PlayerManager
    class ResultManager
    class ScoreManager
    class SoundManager
    class StageAudioManager
    class StageManager
    namespace Calculator{
        class SkillCalculator
        class MovementPatternCalculator
        class EnemyDifficultyCalculator
        class GameOverCalculator
    }
}
namespace Players{
    enum PlayerId
    interface IInputEventProvider
    class PlayerAnimator
    class PlayerCore
    class PlayerEffectEmitter
    class PlayerMover
    class PlayerAttacker
    class PlayerAvoider
    class PlayerJumper
    class PlayerRecover
    namespace Gimmick{
        class ElectromagneticBarrier
        class AI
        class MindReading
        class TimeManipulation
    }
}
namespace Stages{
    enum weather{
        Sunny
        Rainy
        Cloudy
        Windy
        Humid
        Dry
        Stormy
        Snowy
        Foggy
        Dark
        Frosty
    }
    enum Timezone{
        Morning
        Noon
        Night
    }
    namespace Gimmick{
        class WeatherGimmick
        class ElectricBomb
        class ToolSwitching
        class SpecialTool1
        class SpecialTool2
        class SpecialTool3
        class SpecialTool4
    }
}
namespace Title{
    namespace Manager{
        class TitleManager
    }
    namespace Controller{
        class UIController
    }
    namespace View{
        class ChooseButton
    }
}
namespace UIs{
    class ResultController
    class StageUIController
}
@enduml